/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  tutorialSidebar: [
    {
      type: 'category',
      label: '🚀 Getting Started',
      link: { type: 'generated-index' },
      items: [{ type: 'autogenerated', dirName: '01-getting-started' }],
    },
    {
      type: 'category',
      label: '🖥️ System Preparation',
      link: { type: 'generated-index' },
      items: [{ type: 'autogenerated', dirName: '02-system-preparation' }],
    },
    {
      type: 'category',
      label: '🌐 Network Configuration',
      link: { type: 'generated-index' },
      items: [{ type: 'autogenerated', dirName: '03-network-configuration' }],
    },
    {
      type: 'category',
      label: '⏱️ Timing & Synchronization',
      link: { type: 'generated-index' },
      items: [{ type: 'autogenerated', dirName: '04-timing-synchronization' }],
    },
    {
      type: 'category',
      label: '📡 RAN Deployment',
      link: { type: 'generated-index' },
      items: [{ type: 'autogenerated', dirName: '05-ran-deployment' }],
    },
    {
      type: 'category',
      label: '☁️ Core Network',
      link: { type: 'generated-index' },
      items: [{ type: 'autogenerated', dirName: '06-core-network' }],
    },
    {
      type: 'category',
      label: '🧪 Integration & Testing',
      link: { type: 'generated-index' },
      items: [{ type: 'autogenerated', dirName: '07-integration-testing' }],
    },
    {
      type: 'category',
      label: '☸️ Kubernetes Deployment',
      link: { type: 'generated-index' },
      items: [{ type: 'autogenerated', dirName: '08-kubernetes-deployment' }],
    },
    {
      type: 'category',
      label: '⚡ Advanced Topics',
      link: { type: 'generated-index' },
      items: [{ type: 'autogenerated', dirName: '09-advanced-topics' }],
    },
    {
      type: 'category',
      label: '📚 Reference',
      link: { type: 'generated-index' },
      items: [{ type: 'autogenerated', dirName: '10-reference' }],
    },
  ],
};

module.exports = sidebars;
